src/Entity/Dishes.php
<?php

namespace App\Entity;

use App\Repository\DishesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DishesRepository::class)
 */
class Dishes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */

    //  here ManyToOne becasue Many dishes belongs to one category
    /**
     * Undocumented variable
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="dishes")
     */
    private $category;

    private $Description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    
}

src/Controller/DishesController.php
<?php

namespace App\Controller;

use App\Entity\Dishes;
use App\Form\DishesFormType;
use App\Repository\DishesRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

// Main Router to handle all
/**
 * @Route("/dishes", name="appdishes.")
 */

class DishesController extends AbstractController
{
    /**
     * @Route("/dish", name="dish")
     */
    public function index(DishesRepository $dishesdisplay): Response
    {
        $dishesdisplay = $dishesdisplay->findAll();
        return $this->render('dishes/index.html.twig', [
            'dishes' => $dishesdisplay,
        ]);
    }

    /**
     * Undocumented function
     *
     * @param Request $request
     * @param ManagerRegistry $doctrine
     * @return Response
     * @Route("/create", name="create")
     */
    public function create(Request $request, ManagerRegistry $doctrine, SluggerInterface $slugger): Response
    {
        // Create Dish
        $dish = new Dishes();
        // $dish->setName('Pizza');
        // $dish->setDescription('Our Best Pizza');

        // instead of above we make form to add data
        $form = $this->createForm(DishesFormType::class, $dish);

        // now store data in DB using form
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()){
            $entityManager = $doctrine->getManager();

            // Image Upload
            $imagefile = $form->get('attachment')->getData();
            if($imagefile){
                // $originalFileName = pathinfo($imagefile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL

                // First method to set file name, plus add slug and unique file name
                // $safeFilename = $slugger->slug($originalFileName);
                // $FileNamePlusSlug = $safeFilename.'-'.uniqid().'.'.$imagefile->guessExtension();
                
                // another unique name like md5
                $uniqueFilename =  md5(uniqid()) . '.' . $imagefile->guessExtension();
            }

            // Move the file to the directory where brochures are stored (in config/services.yaml)
            $imagefile->move(
                $this->getParameter('broucher_directory'),
                $uniqueFilename
            );
            
            $dish->setImage($uniqueFilename);
            $entityManager->persist($dish);
            $entityManager->flush();
            $this->addFlash('imagesuccess', 'Image Uploaded Successfully');
            return $this->redirect($this->generateUrl('appdishes.dish'));
        }

        return $this->render('dishes/create.html.twig', [
            'formview' => $form->createView(),
        ]);
        


        // Store in the database, need entityManager
        // $entityManager = $doctrine->getManager();
        // $entityManager->persist($dish);
        
        
        // Store in DB
        // $entityManager->flush();

        // Response
        // return new response("Dish created Successfully!!");

       
    }

    /**
     * Undocumented function
     *
     * @Route("/delete/{id}", name="delete")
     */
    public function delete($id, DishesRepository $dishesRepository, ManagerRegistry $doctrine)
    {
        $getitem = $dishesRepository->find($id);
        // entity Manager
        $entityManager = $doctrine->getManager();
        $entityManager->remove($getitem);
        $entityManager->flush();

        // Flash Messages in Symfony
        $this->addFlash('success', 'Deleted Successfully');

        return $this->redirect($this->generateUrl('appdishes.dish'));
    }

    /**
     * Undocumented function
     *
     * @Route("/show/{id}", name="show")
     */
    public function show(Dishes $dishes){
        // In parameters, we can also do same we did in remove, but it's another short method called @paramconverter
        // using paramconverter, we can easily access, id, name and all fields in database
        
        // dump($dishes);
        // die();
        return $this->render('dishes/show.html.twig', [
            'showdish' => $dishes,
        ]);
    }

    /**
     * Undocumented function
     *
     * @param [type] $id
     * @Route("/price/{id}", name="price")
     */
    public function price($id, DishesRepository $dishesRepository)
    {
            $dishes = $dishesRepository->findFiveEur($id);
            dd($dishes);
    }
}

templates/dishes/create.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<div class="container">
 {{ form(formview) }}
</div>
{% endblock %}

templates/dishes/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    {# Delete Flash Messages #}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    {# Image Flash Message #}
    {% for message in app.flashes('imagesuccess') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    
    {# flash message for the login #}
    {% for message in app.flashes('usersuccess') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    {# Display All dishes #}
    <div class="container">
   
    <h3>Dishes Detail</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Order No: </td>
                <td>Dish Name:</td>
                <td>Dish Category:</td>
                <td>Dish Detail: </td>
                <td>Dish Price: </td>
                <td>Delete </td>
                <td> <a href="{{ path('appdishes.create') }}">Create</a></td>
            </tr>
        </thead>
        <tbody>
            {% for dish in dishes %}
                <tr>
                    <td>{{ dish.id }}</td>
                    <td><a href="{{ path('appdishes.show', {id: dish.id}) }}">{{dish.name}}</a></td>
                    <td>{{ dish.Category }}</td> {# happened because of relation between them #}
                    <td>{{ dish.description }}</td>
                    <td>{{ dish.price}}</td>
                    {# <td>price</td> #}
                    <td><a href="{{ path('appdishes.delete', {id : dish.id}) }}">Delete</a></td>
                    <td>X2</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

templates/dishes/show.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<div class="container">
    <h3>Image Name:  {{ showdish.name }}</h3>
    <img src="{{ asset('imagesUpload/brochures/' ~ showdish.image) }}">
</div>
{% endblock %}